// Temp data list
// https://api.coingecko.com/api/v3/coins/list
export default [
  {
    value: 'bitcoin',
    symbol: 'btc',
    name: 'Bitcoin',
    balance: 12,
    currencyValue: 456.99,
  },
  {
    value: 'ethereum',
    symbol: 'eth',
    name: 'Ethereum',
    balance: 2,
    currencyValue: 412356,
  },
  {
    value: 'tether',
    symbol: 'usdt',
    name: 'Tether',
    balance: 0.001,
    currencyValue: 4522216,
  },
  {
    value: 'cardano',
    symbol: 'ada',
    name: 'Cardano',
    balance: 5455,
    currencyValue: 6,
  },
  {
    value: 'binancecoin',
    symbol: 'bnb',
    name: 'Binance Coin',
    balance: 872432,
    currencyValue: 123456,
  },
  {
    value: 'dogecoin',
    symbol: 'doge',
    name: 'Dogecoin',
    balance: 567,
    currencyValue: 4566.9,
  },
  {
    value: 'ripple',
    symbol: 'xrp',
    name: 'XRP',
    balance: 1123,
    currencyValue: 677.34,
  },
  {
    value: 'usd-coin',
    symbol: 'usdc',
    name: 'USD Coin',
    balance: 1110,
    currencyValue: 987234.45,
  },
  {
    value: 'polkadot',
    symbol: 'dot',
    name: 'Polkadot',
    balance: 90,
    currencyValue: 888.9,
  },
  {
    value: 'stellar',
    symbol: 'xlm',
    name: 'Stellar',
    balance: 45,
    currencyValue: 100.0,
  },
  {
    value: 'matic-network',
    symbol: 'matic',
    name: 'Polygon',
    balance: 80,
    currencyValue: 5554.67,
  },
  {
    value: 'solana',
    symbol: 'sol',
    name: 'Solana',
    balance: 801,
    currencyValue: 56664.67,
  },
  {
    value: 'vechain',
    symbol: 'vet',
    name: 'VeChain',
    balance: 19.9,
    currencyValue: 214.9,
  },
  {
    value: 'theta-token',
    symbol: 'theta',
    name: 'Theta Network',
    balance: 3451234.9,
    currencyValue: 214.9,
  },
];
